// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections;
using System.Collections.Generic;
using Foundation;
using SoundCloudClone.Models.App;
using UIKit;

namespace SoundCloudClone.iOS.Controls
{
	public partial class SearchResultsViewController : UIViewController, IUITableViewDataSource
	{
        private List<SearchSuggestion> _results = new List<SearchSuggestion>();

		public SearchResultsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            SearchResultsTableView.DataSource = this;
        }

        public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("SearchResultCell", indexPath) as SearchResultsCell;

            cell.Update(_results[indexPath.Row]);

            return cell;
        }

        public nint RowsInSection(UITableView tableView, nint section)
        {
            return _results.Count;
        }

        internal void UpdateResults(IList newItems)
        {
            _results.Clear();

            foreach (SearchSuggestion item in newItems)
                _results.Add(item);

            SearchResultsTableView.ReloadData();
        }
    }
}
