// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections;
using System.Collections.Generic;
using CoreGraphics;
using Foundation;
using SoundCloudClone.Models.App;
using UIKit;

namespace SoundCloudClone.iOS.Controls
{
	public partial class SearchResultsViewController : UIViewController, IUITableViewDataSource, IUITableViewDelegate
	{
        private List<SearchSuggestion> _results = new List<SearchSuggestion>();
        private UIColor _cellTextColor = UIColor.Clear;

        public event EventHandler<SearchSuggestion> SuggestionSelected;

		public SearchResultsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            SearchResultsTableView.DataSource = this;
            SearchResultsTableView.Delegate = this;
        }

        public override void ViewDidLayoutSubviews()
        {
            base.ViewDidLayoutSubviews();

            UpdateViewHeight();
        }

        public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("SearchResultCell", indexPath) as SearchResultsCell;

            cell.Update(_results[indexPath.Row]);
            cell.ChangeStyle(_cellTextColor);
            cell.ChangeFont();

            return cell;
        }

        public nint RowsInSection(UITableView tableView, nint section)
        {
            return _results.Count;
        }

        internal void ClearResults()
        {
            _results.Clear();
            SearchResultsTableView.ReloadData();
            UpdateViewHeight();
        }

        internal void UpdateResults(IList newItems)
        {
            _results.Clear();

            foreach (SearchSuggestion item in newItems)
                _results.Add(item);

            SearchResultsTableView.ReloadData();
            UpdateViewHeight();
        }

        private void UpdateViewHeight()
        {
            View.Frame = new CGRect(
                View.Frame.X,
                -44,
                View.Frame.Width,
                SearchResultsTableView.ContentSize.Height
            );
        }

        internal void ChangeStyle(UIColor tableViewBackgroundColor, UIColor cellTextColor, UIColor separatorItemBackground)
        {
            SearchResultsTableView.BackgroundColor = tableViewBackgroundColor;
            SearchResultsTableView.SeparatorColor = separatorItemBackground;
            _cellTextColor = cellTextColor;
        }

        [Export("tableView:didSelectRowAtIndexPath:")]
        public void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            SuggestionSelected?.Invoke(this, _results[indexPath.Row]);
            DismissViewController(true, null);
        }
    }
}
